<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:com.corticon.rulesemf.canonicalvocabularymodel="http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="http://root/1.0" nsPrefix="root">
  <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
    <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:RootExtension" majorVersionNumber="6" minorVersionNumber="3" majorServiceNumber="1" minorServiceNumber="2" buildNumber="8020" updateStamp="__4mSc_WdEe2Xd_vkfa_nPw" externalChecksum="3391387159:507989954" studioType="Java" customDataTypeDisplayCount="48">
      <languageCode>en_US</languageCode>
      <databaseAccess databasePropertyDisplayCount="50"/>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//risk_assessment_type">
        <dataTypeName manuallyCreated="true" value="risk_assessment_type"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Criticality'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Health'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//criticality_component_name">
        <dataTypeName manuallyCreated="true" value="criticality_component_name"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Safety Impact'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Environmental Impact'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Generation Impact'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Maintenance Impact'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Spares availability'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//criticality_measures">
        <dataTypeName manuallyCreated="true" value="criticality_measures"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Injury from failure'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Injury during repair'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Air emissions'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Chemical spills'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Water and Process Water Impacts'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Solid and Hazardous Waste'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Capacity Impact'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Downtime Impact'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Equpment Utilization'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Frequency of Failure'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Equipment Redundancy'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Mean time to repair'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Maintenace schedule compliance'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Repair costs'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Spares availability'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//gas_measure">
        <dataTypeName manuallyCreated="true" value="gas_measure"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'H PPM'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'CO2 PPM'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'CH4 PPM'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'C2H6 PPM'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'C2H4 PPM'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'C2H2 PPM'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'CO PPM'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'2FAL Furans PPB'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//tier1_data_quality">
        <dataTypeName manuallyCreated="true" value="tier1_data_quality"/>
        <baseDataType manuallyCreated="true" value="Integer"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="0"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="4"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="7"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="10"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//health_test_name">
        <dataTypeName manuallyCreated="true" value="health_test_name"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Turns Ratio Test'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Short Circuit Impedance Test'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Core-to-Ground Resistance (Megger) Test'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Winding DC Resistance measurement'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Ultrasonic and Sonic Fault Detection'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Vibration Analysis'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Frequency Response Analysis'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Internal Inspection'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Degree of Polymerization'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Other Specialized Diagnostic Tests'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Infrared'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'EMI Survey'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Visual Inspection'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//measure_type">
        <dataTypeName manuallyCreated="true" value="measure_type"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Gas Measurement'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Criticality Analysis'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Tier 1 Condition Indicator'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Tier 2 Condition Indicator'"/>
        </enumerationElements>
      </customDataTypeList>
    </contents>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Asset">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Asset"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="in_service_date" eType="ecore:EDataType http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore#//Date">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="in_service_date"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age_years" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="age_years"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asset_assessments" upperBound="-1" eType="#//Assessment" eOpposite="#//Assessment/asset">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="asset_assessments"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameplate_voltage_ratio_decimal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="nameplate_voltage_ratio_decimal"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Index">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Index"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="note" upperBound="-1" eType="#//Note">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="note"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index_name" eType="#//risk_assessment_type">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.0">
          <name manuallyCreated="true" value="index_name"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assessment" lowerBound="1" eType="#//Assessment" eOpposite="#//Assessment/index">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="assessment"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measure" upperBound="-1" eType="#//Measure" eOpposite="#//Measure/index">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="measure"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index_Component" upperBound="-1" eType="#//Index_Component" eOpposite="#//Index_Component/index">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="index_Component"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="score"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adjustments" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="adjustments"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assessment">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Assessment"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asset" lowerBound="1" eType="#//Asset" eOpposite="#//Asset/asset_assessments">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="asset"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="criticality_score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="criticality_score"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indicator_score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="indicator_score"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" upperBound="-1" eType="#//Index" eOpposite="#//Index/assessment">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="index"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tier1_condition_index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="tier1_condition_index"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tier1_data_quality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="tier1_data_quality"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore#//Date">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="date"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="combined_score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="combined_score"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="health_score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="health_score"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="risk_assessment_type">
    <eLiterals name="V0" literal="'Criticality'"/>
    <eLiterals name="V1" value="1" literal="'Health'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Note">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Note"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="content"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="criticality_measures">
    <eLiterals name="V0" literal="'Injury from failure'"/>
    <eLiterals name="V1" value="1" literal="'Injury during repair'"/>
    <eLiterals name="V2" value="2" literal="'Air emissions'"/>
    <eLiterals name="V3" value="3" literal="'Chemical spills'"/>
    <eLiterals name="V4" value="4" literal="'Water and Process Water Impacts'"/>
    <eLiterals name="V5" value="5" literal="'Solid and Hazardous Waste'"/>
    <eLiterals name="V6" value="6" literal="'Capacity Impact'"/>
    <eLiterals name="V7" value="7" literal="'Downtime Impact'"/>
    <eLiterals name="V8" value="8" literal="'Equpment Utilization'"/>
    <eLiterals name="V9" value="9" literal="'Frequency of Failure'"/>
    <eLiterals name="V10" value="10" literal="'Equipment Redundancy'"/>
    <eLiterals name="V11" value="11" literal="'Mean time to repair'"/>
    <eLiterals name="V12" value="12" literal="'Maintenace schedule compliance'"/>
    <eLiterals name="V13" value="13" literal="'Repair costs'"/>
    <eLiterals name="V14" value="14" literal="'Spares availability'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="gas_measure">
    <eLiterals name="V0" literal="'H PPM'"/>
    <eLiterals name="V1" value="1" literal="'CO2 PPM'"/>
    <eLiterals name="V2" value="2" literal="'CH4 PPM'"/>
    <eLiterals name="V3" value="3" literal="'C2H6 PPM'"/>
    <eLiterals name="V4" value="4" literal="'C2H4 PPM'"/>
    <eLiterals name="V5" value="5" literal="'C2H2 PPM'"/>
    <eLiterals name="V6" value="6" literal="'CO PPM'"/>
    <eLiterals name="V7" value="7" literal="'2FAL Furans PPB'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="criticality_component_name">
    <eLiterals name="V0" literal="'Safety Impact'"/>
    <eLiterals name="V1" value="1" literal="'Environmental Impact'"/>
    <eLiterals name="V2" value="2" literal="'Generation Impact'"/>
    <eLiterals name="V3" value="3" literal="'Maintenance Impact'"/>
    <eLiterals name="V4" value="4" literal="'Spares availability'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Measure">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Measure"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" lowerBound="1" eType="#//Index" eOpposite="#//Index/measure">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="index"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gas_measure" eType="#//gas_measure">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.3">
          <name manuallyCreated="true" value="gas_measure"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measure_value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="measure_value"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index_Component" lowerBound="1" eType="#//Index_Component" eOpposite="#//Index_Component/measure">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="index_Component"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="observation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="observation"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measure_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="measure_name"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="raw_score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="raw_score"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="weight"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weighted_value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="weighted_value"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measure_type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="measure_type"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Index_Component">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Index_Component"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="criticality_component_name" eType="#//criticality_component_name">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.1">
          <name manuallyCreated="true" value="criticality_component_name"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measure" upperBound="-1" eType="#//Measure" eOpposite="#//Measure/index_Component">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="measure"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" lowerBound="1" eType="#//Index" eOpposite="#//Index/index_Component">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="index"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="health_component_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="health_component_name"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="health_component_raw_score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="health_component_raw_score"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="health_test_name" eType="#//health_test_name">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.5">
          <name manuallyCreated="true" value="health_test_name"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="health_component_weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="health_component_weight"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="health_component_score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="health_component_score"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="health_adjustment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="health_adjustment"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="note" upperBound="-1" eType="#//Note">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="note"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="criticality_component_net_score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="criticality_component_net_score"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="tier1_data_quality">
    <eLiterals name="V0" literal="0"/>
    <eLiterals name="V1" value="1" literal="4"/>
    <eLiterals name="V2" value="2" literal="7"/>
    <eLiterals name="V3" value="3" literal="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="health_test_name">
    <eLiterals name="V0" literal="'Turns Ratio Test'"/>
    <eLiterals name="V1" value="1" literal="'Short Circuit Impedance Test'"/>
    <eLiterals name="V2" value="2" literal="'Core-to-Ground Resistance (Megger) Test'"/>
    <eLiterals name="V3" value="3" literal="'Winding DC Resistance measurement'"/>
    <eLiterals name="V4" value="4" literal="'Ultrasonic and Sonic Fault Detection'"/>
    <eLiterals name="V5" value="5" literal="'Vibration Analysis'"/>
    <eLiterals name="V6" value="6" literal="'Frequency Response Analysis'"/>
    <eLiterals name="V7" value="7" literal="'Internal Inspection'"/>
    <eLiterals name="V8" value="8" literal="'Degree of Polymerization'"/>
    <eLiterals name="V9" value="9" literal="'Other Specialized Diagnostic Tests'"/>
    <eLiterals name="V10" value="10" literal="'Infrared'"/>
    <eLiterals name="V11" value="11" literal="'EMI Survey'"/>
    <eLiterals name="V12" value="12" literal="'Visual Inspection'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="measure_type">
    <eLiterals name="V0" literal="'Gas Measurement'"/>
    <eLiterals name="V1" value="1" literal="'Criticality Analysis'"/>
    <eLiterals name="V2" value="2" literal="'Tier 1 Condition Indicator'"/>
    <eLiterals name="V3" value="3" literal="'Tier 2 Condition Indicator'"/>
  </eClassifiers>
</ecore:EPackage>
